name: "Nimbus Action"
description: "A CD solution that deploys projects to your self-hosted servers."
inputs:
  nimbus-server:
    description: "URL of the Nimbus server."
    required: true
  api-key:
    description: "API key for the Nimbus server."
    required: true
  nimbus-path:
    description: "Path to the nimbus file."
    required: false
    default: "./nimbus.yaml"
outputs:
  service-urls:
    description: "List of URLs of the services deployed."
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    NIMBUS_SERVER: ${{ inputs.nimbus-server }}
    NIMBUS_API_KEY: ${{ inputs.api-key }}
    NIMBUS_PATH: ${{ inputs.nimbus-path }}
branding:
  icon: "arrow-right"
  color: "green"
