name: "Nimbus Action"
description: "A CD solution that deploys projects to your self-hosted servers."
inputs:
  nimbus-path:
    description: "Path to the nimbus file."
    required: false
    default: "./nimbus.yaml"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.nimbus-path }}
