name: "Nimbus Action"
description: "A CD solution that deploys projects to your self-hosted servers."
inputs:
  nimbus-server:
    description: "URL of the Nimbus server."
    required: true
  api-key:
    description: "API key to authenticate with the Nimbus server."
    required: true
  nimbus-path:
    description: "Path to the nimbus file."
    required: false
    default: "./nimbus.yaml"
outputs:
  service-urls:
    description: "List of URLs of the services deployed."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.nimbus-path }}
