app: nimbus
services:
  - name: frontend
    template: http
    image: matthew10125/boshi-frontend
    env:
      - name: BACKEND_URL
        value: ${FRONTEND_BACKEND_URL}
    network:
      ports:
        - 80

  - name: backend
    template: http
    image: matthew10125/boshi-backend
    env:
      - name: DATABASE_URL
        value: ${BACKEND_PG_URL}
      - name: SECRET_KEY
        value: ${BACKEND_SECRET_KEY}
    network:
      ports:
        - 80

  - name: database
    template: postgres
    version: 13.3
    env:
      - name: POSTGRES_USER
        value: ${DATABASE_USER}
      - name: POSTGRES_PASSWORD
        value: ${DATABASE_PASSWORD}
    configs:
      - path: /etc/configs/default.conf
        value: |
          key=value

  - name: redis
    template: redis
