app: nimbus-test
allowBranchPreviews: true
services:
  - name: http-test
    public: true
    template: http
    image: hashicorp/http-echo
    network:
      ports:
        - 8080
    args: ["-listen=:8080", "-text=Hello from Nimbus!"]
    # Custom ingress annotations are merged on top of Nimbus' defaults, so you
    # can append new ones or override the built-ins (only applied to public
    # http services).
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-url: "https://idp.prayujt.com/sessions/whoami"
      nginx.ingress.kubernetes.io/auth-signin: "https://proxy.prayujt.com/oauth2/start?rd=$scheme://$host$request_uri"

  - name: database
    template: postgres
    version: 13.3
    env:
      - name: POSTGRES_USER
        value: ${DATABASE_USER}
      - name: POSTGRES_PASSWORD
        value: ${DATABASE_PASSWORD}
    configs:
      - path: /etc/configs/default.conf
        value: |
          key=value

  - name: redis
    template: redis
