app: nimbus-test
allowBranchPreviews: true
services:
  - name: http-test
    public: true
    template: http
    image: hashicorp/http-echo
    network:
      ports:
        - 8080
    args: ["-listen=:8080", "-text=Hello from Nimbus!"]

  - name: database
    template: postgres
    version: 13.3
    env:
      - name: POSTGRES_USER
        value: ${DATABASE_USER}
      - name: POSTGRES_PASSWORD
        value: ${DATABASE_PASSWORD}
    configs:
      - path: /etc/configs/default.conf
        value: |
          key=value

  - name: redis
    template: redis
