app: nimbus-test
allowBranchPreviews: true
services:
  - name: http-test
    public: true
    template: http
    image: hashicorp/http-echo:1.0.0
    network:
      ports:
        - 8080
    args: ["-listen=:8080", "-text=Hello from Nimbus!"]
    annotations:
      envoy.nimbus.dev/ssl-redirect: "true"
