name: Test Action

on: [push]

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Nimbus Action
        id: test-action
        uses: ./
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        with:
          api-key: ${{ secrets.NIMBUS_API_KEY }}
          nimbus-server: ${{ secrets.NIMBUS_URL }}
          nimbus-path: nimbus.yaml

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.service-urls }}"
